# -*- coding: utf-8 -*-
"""200901034_assignment_04_OPERATING_SYSTEM

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qGMGAUfx2TVKyeDziXiUsPEE6otQUTLi
"""

import threading
import time
string='' 
def input_function():
   print('')
   print('            -----Input thread has been started------')
   print('')
   global string  
   while True:
     string= input("Enter a String: ") 
     string1=string.replace(" ", "")
     try:
        string1 = str(string1)
        if not string1.isalpha():
          raise ValueError
     except ValueError:
       print('You did not enter valid string')
       print('Try again please')
       continue
     else:
       return string
def reverse_function():
    global string  
    print('')
    print('')
    print('            -----Reverse thread has been started------')
    print('')
    print("Reverse string:  ",string[::-1])
    print('')
def capitalize_function():
    global string   
    print('')
    print('            -----Capitalize thread has been started------')
    print('')
    print("capitalize  string:  ",string.upper())
    print('')
def shift_function():
    global string 
    print('')
    print('            -----Shift thread has been started------')
    print('')  
    data=[]
    for i in string:
        if i.strip() and i in strs:
            data.append(strs[(strs.index(i) + 2) % 26])
        elif i.strip() and i in STRS:
            data.append(STRS[(STRS.index(i) + 2) % 26])
        else:
            data.append(i)
    output=''.join(data)
    print("shifting character:  ",output)
    print('')
   
strs='abcdefghijklmnopqrstuvwxyz'
STRS='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
t1 = threading.Thread(target=input_function, name='t1')
t2 = threading.Thread(target=reverse_function, name='t2')
t3 = threading.Thread(target=capitalize_function, name='t3')
t4 = threading.Thread(target=shift_function, name='t4')
t1.start()  
t1.join() 
t2.start()
t2.join()   
t3.start()
t3.join()
t4.start() 
t4.join()
print('')
print('               -------THANK YOU------')

